<?php

/**
 * Node_Model_Base_Story
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Node_Model_Story_Fields $Fields
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Node_Model_Base_Story extends Node_Model_Node
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node_Model_Story_Fields as Fields', array(
             'local' => 'id',
             'foreign' => 'node_id'));
    }
}