<?php

/**
 * Menu_Model_Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage Menu
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Menu_Model_Menu extends Menu_Model_Base_Menu
{
    
    public function getContainer()
    {
        $container = new Zend_Navigation();
        $items = $this->getChildItems();
        foreach ($items as $item) {
            $page = $item->getPage();
            $container->addPage($page);
        }
        return $container;
    }
    
    public function getChildItems($menuId = NULL, $parentId = NULL)
    {
        if (!$menuId) {
            $menuId = $this->id;
        }
        
        $q = Doctrine_Query::create()
            ->from('Menu_Model_Item')
            ->where('menu_id = ?', $menuId);
        
        if ($parentId) {
            $q->andWhere('parent_id = ?', $parentId);
        }
        else {
            $q->andWhere('parent_id IS NULL');
        }

        $q->orderBy('weight, label');
        
        return $q->execute();
    }

//    public static function getTermsByMenuId($menuId)
//    {
//        
//        $items = self::getChildItems($menuId);
//        foreach ($items as $item) {
//            $items->Items = self::get
//        }
//        $q = Doctrine_Query::create()
//            ->from('Taxonomy_Model_Term')
//            ->where('vocabulary_id = ?', $menuId)
//            ->orderBy('weight, name');
//        
//        return $q->execute();
//    }
//
//    public static function getVocabulariesByNodetypeId($id = NULL)
//    {
//        if ($id) {
//            $q = Doctrine_Query::create()
//                ->select('v.*')
//                ->addFrom('Taxonomy_Model_Vocabulary v')
//                ->addFrom('Taxonomy_Model_VocabularyNodetype vn')
//                ->where('v.id = vn.vocabulary_id')
//                ->andWhere('vn.nodetype_id = ?', $id)
//                ->orderBy('weight, name');
//        }
//        else {
//            $q = Doctrine_Query::create()
//                ->from('Taxonomy_Model_Vocabulary')
//                ->orderBy('weight, name');
//        }
//
//        return $q->execute();
//    }
}