<?php

/**
 * Taxonomy_Model_VocabularyNodetype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Taxonomy_Model_VocabularyNodetype extends Taxonomy_Model_Base_VocabularyNodetype
{

}