<?php

/**
 * Path_Model_Base_TypeRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nodetype_id
 * @property string $route
 * @property Node_Model_Type $Type
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Path_Model_Base_TypeRoute extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('nodetype_route');
        $this->hasColumn('nodetype_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node_Model_Type as Type', array(
             'local' => 'nodetype_id',
             'foreign' => 'id'));
    }
}