<?php

/**
 * Node_Model_Base_Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Node_Model_Base_Page extends Node_Model_Node
{
    public function setUp()
    {
        parent::setUp();
        
    }
}