<?php

/**
 * Taxonomy_Model_Base_NodeTerm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $node_id
 * @property integer $term_id
 * @property Node_Model_Node $Node
 * @property Taxonomy_Model_Term $Term
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Taxonomy_Model_Base_NodeTerm extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('node_term');
        $this->hasColumn('node_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('term_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node_Model_Node as Node', array(
             'local' => 'node_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Taxonomy_Model_Term as Term', array(
             'local' => 'term_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}