<?php

/**
 * Taxonomy_Model_Base_Term
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vocabulary_id
 * @property string $name
 * @property clob $description
 * @property integer $weight
 * @property Taxonomy_Model_Vocabulary $Vocabulary
 * @property Doctrine_Collection $Nodes
 * @property Doctrine_Collection $Taxonomy_Model_NodeTerm
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Taxonomy_Model_Base_Term extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('term');
        $this->hasColumn('vocabulary_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '80',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Taxonomy_Model_Vocabulary as Vocabulary', array(
             'local' => 'vocabulary_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Node_Model_Node as Nodes', array(
             'refClass' => 'Taxonomy_Model_NodeTerm',
             'local' => 'term_id',
             'foreign' => 'node_id'));

        $this->hasMany('Taxonomy_Model_NodeTerm', array(
             'local' => 'id',
             'foreign' => 'term_id'));
    }
}