<p>Pinciuc.com is the personal website of Rob Pinciuc, a Toronto-based web developer and amateur photographer.</p>

<p>This website is running on a custom-built server computer, designed to run silently. The VMWare ESX 4 operating system was chosen to provision multiple virtual machines on one server computer, saving energy and utilizing resources more efficiently. Ubuntu Server was chosen for it's stability, ease of maintenance and large support community.</p>

<p>This is the fourth incarnation of pinciuc.com, and is built using a new, extensible Content Management System (CMS) called <em>EPIC</em>. <em>EPIC</em> is created by Rob Pinciuc, is built on <em><a href="http://framework.zend.com/">Zend Framework</a></em> and is designed to mimic some of the functionality of <em><a href="http://www.drupal.org/">Drupal</a></em>, whilst utilizing object-oriented design best practices and design patterns. More information about <em>EPIC</em>, including source code downloads, may be available in the future.</p>

<h3>Networking Hardware</h3>

<ul>
<li>Cisco 837 Router</li>
<li>Dell PowerConnect 2608 Gigabit Ethernet Switch</li>
</ul>

<h3>Server Hardware</h3>

<ul>
<li>Antec P182 Super Mid Tower Case</li>
<li>Corsair HX520W Modular Power Supply</li>
<li>Gigabyte GA-965P-DS3 Motherboard</li>
<li>Intel Core 2 Quad Q6600 (Kentsfield) 2.4GHz w/ 8MB L2 Cache CPU</li>
<li>8GB (4x2GB) Corsair XMS2 PC2-6400 DDR2 @ 800MHz</li>
<li>Pioneer DVR-212D SATA DVD/CD Writer</li>
<li>Seagate Barracuda 7200.10 500GB SATA2 Hard Disk (System)</li>
<li>3ware 9650SE-8LPML 8-port SATA2 PCI-e RAID Controller</li>
<li>4 x Seagate Barracuda 7200.11 1TB SATA2 Hard Disk (in RAID5 - 3TB)</li>
<li>Chenbro SK33502-BK 5-in-3 Hot-swap SATA Storage Enclosure</li>
<li>Intel Pro/1000 PT PCI-e Gigabit Ethernet Adapter</li>
<li>Multiple Nexus 80mm/92mm/120mm Real Silent Case Fans</li>
</ul>

<h3>Server Software</h3>

<ul>
<li>VMWare ESX 4 64-bit Operating System</li>
<li>Multiple Ubuntu Linux 64-bit Servers (in Virtual Machines)</li>
<li>Apache Web Server</li>
<li>PHP 5</li>
<li>EPIC Content Management System</li>
<li>Zend Framework</li>
<li>MySQL Server</li>
</ul>
