<p>All photographs, text, graphics and other content appearing in this website, www.pinciuc.com, are the exclusive property of Rob Pinciuc (unless otherwise noted) and are protected under Canadian and international copyright laws.</p>

<p>The photographs MAY NOT BE reproduced, copied, stored, manipulated, projected, used or altered in any way, including without limitation, any digitalization or synthesizing of the images, alone or with any other material, by use of computer or other electronic means or any other method or means now or hereafter known, without the written permission of Rob Pinciuc and payment of a fee or arrangement thereof.</p>

<p>No images are within Public Domain. Use of any image as the basis for another photographic concept or illustration is a violation of copyright.</p>

<p>If you wish to use or purchase an image, please <a href="<?= $this->url(array('action' => 'contact')) ?>">contact me</a>.</p>

<p>By viewing this website, you are agreeing to be bound by the terms of this agreement.</p> 