<?php

/**
 * Menu_Model_Base_Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $Items
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Menu_Model_Base_Menu extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('title', 'string', 80, array(
             'type' => 'string',
             'length' => '80',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Menu_Model_Item as Items', array(
             'local' => 'id',
             'foreign' => 'menu_id'));
    }
}