<?php

/**
 * Menu_Model_Base_Route
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $route
 * @property array $defaults
 * @property array $reqs
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Menu_Model_Base_Route extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('route');
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '80',
             ));
        $this->hasColumn('route', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('defaults', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('reqs', 'array', null, array(
             'type' => 'array',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}