<?php //$this->layout()->title = $this->user->username . "'s Profile" ?>
<h2>User Information</h2>

<ul>
<li>Username: <?php echo $this->user->username ?></li>
<li>Email Address: <?php echo $this->escape($this->user->email_address) ?></li>
<li>Roles: 
<?php
    $roles = array();
    foreach ($this->user->Roles as $role) {
        $roles[] = $role->name;
    }
?> 
<?= $this->escape(implode(', ', $roles)) ?>
</li>
</ul>
