<?php

/**
 * User_Model_Base_Privilege
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_id
 * @property string $privilege
 * @property integer $order
 * @property string $description
 * @property User_Model_Resource $Resource
 * @property Doctrine_Collection $Roles
 * @property Doctrine_Collection $User_Model_RolePrivilege
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class User_Model_Base_Privilege extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('privilege');
        $this->hasColumn('resource_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('privilege', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('rank as order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Resource as Resource', array(
             'local' => 'resource_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('User_Model_Role as Roles', array(
             'refClass' => 'User_Model_RolePrivilege',
             'local' => 'privilege_id',
             'foreign' => 'role_id'));

        $this->hasMany('User_Model_RolePrivilege', array(
             'local' => 'id',
             'foreign' => 'privilege_id'));
    }
}