<?php

/**
 * User_Model_Base_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property string $module
 * @property string $resource
 * @property integer $order
 * @property string $description
 * @property User_Model_Resource $Parent
 * @property Doctrine_Collection $Children
 * @property Doctrine_Collection $Privileges
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class User_Model_Base_Resource extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('module', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'default',
             'length' => '40',
             ));
        $this->hasColumn('resource', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('rank as order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Resource as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('User_Model_Resource as Children', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('User_Model_Privilege as Privileges', array(
             'local' => 'id',
             'foreign' => 'resource_id'));
    }
}