<?php

/**
 * User_Model_Base_Session
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $modified
 * @property integer $lifetime
 * @property clob $data
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class User_Model_Base_Session extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('id', 'string', 32, array(
             'type' => 'string',
             'primary' => true,
             'length' => '32',
             ));
        $this->hasColumn('modified', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lifetime', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('data', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}