<?php

/**
 * User_Model_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User_Model_Resource extends User_Model_Base_Resource implements Zend_Acl_Resource_Interface 
{
    
    /**
     * Implementation of Zend_Acl_Resource_Interface.
     * Returns the name of this role.
     *
     * @return string
     */
    public function getResourceId() {
        return $this->module.':'.$this->resource;
    }
    
    // Sorting function.
    function resourceSort($a, $b) {
//        $aName = $a['module'] . ':' . $a['resource'];
//        $bName = $b['module'] . ':' . $b['resource'];
        $aName = $a->getResourceId();
        $bName = $b->getResourceId();
        
        if ($aName == $bName) {
            return 0;
        }
        
        return ($aName > $bName) ? 1 : -1;
    }
    
    public static function getResourceByString($string) {
        list($module, $resource) = explode(':', $string);
        
        $q = Doctrine_Query::create()
                ->from('User_Model_Resource')
                ->where('module = ?', $module)
                ->andWhere('resource = ?', $resource);
                
        $resource = $q->execute();
        
        return $resource[0];
    }
}