<?php

/**
 * User_Model_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage User
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User_Model_Role extends User_Model_Base_Role implements Zend_Acl_Role_Interface
{

    /**
     * Implementation of Zend_Acl_Role_Interface.
     * Returns the name of this role.
     *
     * @return string
     */
    public function getRoleId() {
        return $this->name;
    }
    
    public function isAllowed($resource, $privilege = NULL) {
        if (!$privilege) {
            $privilege = $resource;
        }
        else {
            foreach ($resource->Privileges as $p) {
                if ($p->privilege == $privilege) {
                    $privilege = $p;
                    break;
                }
            }
        }
        
        $q = Doctrine_Query::create()
            ->from('User_Model_RolePrivilege rp')
            ->where('rp.role_id = ?', $this->id)
            ->andWhere('rp.privilege_id = ?', $privilege->id);
            
        $result = $q->fetchOne();
        
        if (isset($result->role_id)) {
            return $result->allowed ? 1 : -1;
        }
        
        return 0;
    }
    
    public function setAllowed($permission, $allowed = TRUE) {
        $q = Doctrine_Query::create()
            ->update('User_Model_RolePermission')
            ->set('allowed', '?', $allowed)
            ->where('role_id = ?', $this->id)
            ->andWhere('permission_id = ?', $permission->id);
            
        $rows = $q->execute();
        
        return $rows;
    }
    
    public function allow($permission)
    {
        return $this->setAllowed($permission, TRUE);
    }

    public function deny($permission)
    {
        return $this->setAllowed($permission, FALSE);
    }

//    public function getChildRoles()
//    {
//        $q = Doctrine_Query::create()
//            ->from('User_Model_Role r')
//            ->addFrom('User_Model_RoleParent rp')
//            ->where('r.id = rp.role_id)')
//            ->andWhere('rp.parent_id = ?', $this->id)
//            ->orderBy('r.name');
        
//        $q = Doctrine_Query::create()
//            ->from('User_Model_Role r')
//            ->where('EXISTS (SELECT rp.role_id FROM User_Model_RoleParent rp WHERE rp.parent_id = ?)', $this->id)
//            ->orderBy('r.name');
        
//        $q = Doctrine_Query::create()
//            ->from('User_Model_Role')
//            ->where('parent_id = ?', $this->id)
//            ->orderBy('name');
        
//        Zend_Debug::dump($q->getSqlQuery());
//        return $q->execute();
//    }
}