<?php

/**
 * Comment_Model_Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Comment_Model_Comment extends Comment_Model_Base_Comment
{

    public static function getChildItems($nodeId, $parentId = NULL)
    {
        $q = Doctrine_Query::create()
            ->from('Comment_Model_Comment c')
            ->where('c.field_comment_node_id = ?', $nodeId);
        
        if ($parentId) {
            $q->andWhere('c.Fields.parent_id = ?', $parentId);
        }
        else {
            $q->andWhere('c.Fields.parent_id IS NULL');
        }

        $q->orderBy('c.created_at, id');
        
        return $q->execute();
    }
}