<?php

/**
 * Taxonomy_Model_Vocabulary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    EPIC
 * @subpackage ##SUBPACKAGE##
 * @author     Rob Pinciuc <rob@pinciuc.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Taxonomy_Model_Vocabulary extends Taxonomy_Model_Base_Vocabulary
{

    public function getTerms()
    {
        return self::getTermsByVocabularyId($this->id);
    }
    
    public static function getTermsByVocabularyId($id)
    {
        
        $q = Doctrine_Query::create()
            ->from('Taxonomy_Model_Term')
            ->where('vocabulary_id = ?', $id)
            ->orderBy('weight, name');
        
        return $q->execute();
    }

    public static function getVocabulariesByNodetypeId($id = NULL)
    {
        if ($id) {
            $q = Doctrine_Query::create()
                ->select('v.*')
                ->addFrom('Taxonomy_Model_Vocabulary v')
                ->addFrom('Taxonomy_Model_VocabularyNodetype vn')
                ->where('v.id = vn.vocabulary_id')
                ->andWhere('vn.nodetype_id = ?', $id)
                ->orderBy('weight, name');
        }
        else {
            $q = Doctrine_Query::create()
                ->select('*')
                ->from('Taxonomy_Model_Vocabulary')
                ->orderBy('weight, name');
        }

        return $q->execute();
    }
}